stages:
  - pre-commit
  - test-suite

pre-commit:
  stage: pre-commit
  image:
    name: registry.gitlab.com/saltstack/open/cicd/containers/py:3.8
  before_script:
    - apt-get update && apt-get install -y git
    - python -m pip install --upgrade pip
    - pip install pre-commit
    - pre-commit install --install-hooks
    - chmod -R g-w,o-w . && umask 0022
  script:
    - pre-commit run --show-diff-on-failure --color=always --all-files

.test-suite:
  stage: test-suite
  needs:
    - pre-commit
  parallel:
    matrix:
      - SALT_REQUIREMENT: [salt~=3003.0, salt~=3004.0]
  before_script:
    - apt-get update
    - apt-get install -y git
    # Pyinstaller system requirements
    - apt-get install -y binutils libc-bin
    # For codecoverage uploads
    - apt-get install -y curl gpg
    - python3 -m pip install nox
  script:
    - nox --force-color -e tests-3 -- -vv --log-cli-level=warning
  artifacts:
    when: always
    paths:
      - artifacts
    reports:
      junit: artifacts/junit-report.xml
    expire_in: 30 days
#  after_script:
#    - set -ex
#    - cicd/upload-code-coverage.sh

linux-3.6:
  extends: .test-suite
  image:
    name: registry.gitlab.com/saltstack/open/cicd/containers/py:3.6

linux-3.7:
  extends: .test-suite
  image:
    name: registry.gitlab.com/saltstack/open/cicd/containers/py:3.7

linux-3.8:
  extends: .test-suite
  image:
    name: registry.gitlab.com/saltstack/open/cicd/containers/py:3.8

linux-3.9:
  extends: .test-suite
  image:
    name: registry.gitlab.com/saltstack/open/cicd/containers/py:3.9

#tests-3.10:
#  extends: .test-suite
#  image:
#    name: registry.gitlab.com/saltstack/open/cicd/containers/py:3.10
